PRINT 'Q1: List of products that are offered by at least one supplier from Chicago'
SELECT DISTINCT P.NAME
FROM TB_OFFERS AS O
INNER JOIN TB_PRODUCT AS P
ON O.PROD_ID=P.PROD_ID
INNER JOIN TB_SUPPLIER AS S
ON O.SUPP_ID=S.SUPP_ID
WHERE S.CITY='Chicago'

PRINT 'Q2: List of offers showing supplier name(as Supplier Name), product name(as Product Name), quantity, price and value'
SELECT S.NAME AS 'SUPPLIER NAME', P.NAME AS 'PRODUCT NAME', O.QUANTITY, O.PRICE, O.QUANTITY*O.PRICE AS VALUE
FROM TB_SUPPLIER AS S
INNER JOIN TB_OFFERS AS O
ON S.SUPP_ID=O.SUPP_ID
INNER JOIN TB_PRODUCT AS P
ON P.PROD_ID=O.PROD_ID

PRINT 'Q3: List of cities with at least 2 consumers'
SELECT CITY
FROM TB_CONSUMER
GROUP BY CITY
HAVING COUNT(con_id)>1

PRINT 'Q4: List of products requested by at least two consumers'
SELECT P.NAME
FROM TB_PRODUCT AS P
INNER JOIN TB_REQUESTS AS R
ON P.PROD_ID=R.PROD_ID
GROUP BY P.NAME
HAVING COUNT(R.CON_ID)>1

PRINT 'Q5: List of cities where at least one product is both offered and requested'
SELECT C.CITY
FROM TB_OFFERS AS O
INNER JOIN TB_PRODUCT AS P
ON O.PROD_ID=P.PROD_ID
INNER JOIN TB_REQUESTS AS R
ON P.PROD_ID=R.PROD_ID
INNER JOIN TB_CONSUMER AS C
ON C.CON_ID=R.CON_ID
INNER JOIN TB_SUPPLIER AS S
ON S.CITY=C.CITY
GROUP BY C.CITY
HAVING COUNT(O.PROD_ID)>0 AND COUNT(R.PROD_ID)>0

PRINT 'Q6: List of suppliers from Madison that have sold computers in Wausau'
SELECT DISTINCT S.NAME
FROM TB_SUPPLIER AS S
INNER JOIN TB_TRANSACTIONS AS T
ON S.SUPP_ID=T.SUPP_ID
INNER JOIN TB_CONSUMER AS C
ON T.CON_ID=C.CON_ID
WHERE S.CITY='Madison' AND C.CITY='Wausau'

PRINT 'Q7: List of consumers that are from Wausau and requested computers or oranges'
SELECT DISTINCT C.NAME
FROM TB_CONSUMER AS C
INNER JOIN TB_REQUESTS AS R
ON C.CON_ID=R.CON_ID
INNER JOIN TB_PRODUCT AS P
ON R.PROD_ID=P.PROD_ID
WHERE P.NAME='Computer' OR P.NAME='Orange'
GROUP BY C.NAME, C.CITY
HAVING C.CITY='Wausau'
	
PRINT 'Q8: List of consumers that bought auto in their own city'
SELECT C.NAME
FROM TB_CONSUMER AS C
INNER JOIN TB_TRANSACTIONS AS T
ON C.CON_ID=T.CON_ID
INNER JOIN TB_PRODUCT AS P
ON T.PROD_ID=P.PROD_ID
INNER JOIN TB_SUPPLIER AS S
ON T.SUPP_ID=S.SUPP_ID
WHERE P.NAME='Auto' AND S.CITY=C.CITY

PRINT 'Q9: List of products offered in Chicago or requested in Madison'
SELECT DISTINCT P.NAME
FROM TB_PRODUCT AS P
INNER JOIN TB_REQUESTS AS R
ON P.PROD_ID=R.PROD_ID
INNER JOIN TB_OFFERS AS O
ON P.PROD_ID=O.PROD_ID
INNER JOIN TB_SUPPLIER AS S
ON O.SUPP_ID=S.SUPP_ID
INNER JOIN TB_CONSUMER AS C
ON R.CON_ID=C.CON_ID
WHERE S.CITY='Chicago' OR C.CITY='Madison'

PRINT 'Q10: List of products that are both requested and offered in Wausau'
SELECT DISTINCT P.NAME
FROM TB_PRODUCT AS P
INNER JOIN TB_REQUESTS AS R
ON P.PROD_ID=R.PROD_ID
INNER JOIN TB_OFFERS AS O
ON P.PROD_ID=O.PROD_ID
INNER JOIN TB_SUPPLIER AS S
ON O.SUPP_ID=S.SUPP_ID
INNER JOIN TB_CONSUMER AS C
ON R.CON_ID=C.CON_ID
WHERE C.CITY='Wausau' AND S.CITY='Wausau'